name: weam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.4+10

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  smooth_page_indicator: ^1.2.0
  flutter_rating_bar: ^4.0.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  path: ^1.9.0
  carousel_slider: ^5.0.1
  cached_network_image: ^3.4.1
  rename: ^3.0.2
  equatable: ^2.0.7
  jiffy: ^6.3.0
  dartz: ^0.10.1
  get_it: ^9.0.5
  meta: ^1.9.0

  # أهم تعديل — حل مشكلة البناء
  flutter_local_notifications: ^19.5.0

  flutter_polyline_points: ^2.1.0
  lottie: ^3.1.3

  google_maps_flutter: ^2.14.0

  easy_localization: ^3.0.4

  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4

  fluttertoast: ^9.0.0
  pin_code_fields: ^8.0.1

  geolocator: ^14.0.2
  geocoding: ^3.0.0

  cloud_firestore: ^4.2.1  # تم تعديله هنا

  flutter_clickpay_bridge: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: almarai
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Light.ttf
        - asset: assets/fonts/Almarai-Regular.ttf